### PR TITLE
2018-05-21 Simplified web startup, current Uno release

### PR DESCRIPTION
**Pull request by MarkStega**
1) Changed the web startup to directly instantiate the playground project

2) Updated to current Uno platform

3) Updated .gitignore to ignore the entire wwwroot folder in the server diectory

### CODE REVIEW

**Comment by MarkStega** [comment]
Note that you can't update to V2 of the Microsoft.Extensions.Logging.Console as it attempts to create threads which, of course, won't work with the current state of mono/wasm. The commits after the initial were my stepwise exploration of which package update broke the wasm project. They are certainly all safe to be rolled into one commit.

**Comment by jeromelaban** [comment]
Thanks mark for your PR!

We're currently setting up CI with Microsoft, and we have to delay the merge a little bit, thanks!

**Comment by carldebilly** [comment]
We really appreciate your contribution into Uno. But the actual sources for the Playground is still yet in our private VSTS repo, because we were waiting for a public VSTS account for the build & publish tasks.

We now have it (<https://uno-platform.visualstudio.com/Uno%20Platform/>), so we'll soon move the _real_ sources here and your changes will be integrated as well.

Thank you again for your support.

**Comment by MarkStega** [comment]
@carldebilly  Thx - Is the Uno repository 'fair game' for PRs or is it also slated for replacement by a VSTS version?

**Comment by carldebilly** [comment]
Hello Mark,

Yes it is the right place.  Sorry for the delay, there was a lot of tweaks on our side to make this working well. PRs will be accepted on this repo very soon.

The VSTS project (<https://uno-platform.visualstudio.com/>) is for the CI+CD part of the process. All other aspects of the playground (issues, source & PRs) will be done here.

Since it's not possible to build Xamarin on _Appveyor_, we're using VSTS build services instead.

**Comment by MarkStega** [comment]
Closing since the changes were migrated outside of the PR

**Comment by carldebilly** [comment]
This won't happend with future PRs.

**Comment by MarkStega** [comment]
I completely understand; not an issue at all...

**Pull request closed without merging**
